services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: food-ordering-and-tracking-app:latest
    container_name: food-ordering-app
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017
      - INIT_ADMIN_NAME=admin
      - INIT_ADMIN_API_KEY=true
      # Generate your own secret for production use (openssl rand -base64 32)
      # For example, a random base64 string (don't use this in production):
      # - COOKIE_SECRET=vyH37xWoS4pItUt+od48PY4jU0/3qzfPgK1t5fJr8Fs=
      - COOKIE_SECRET=vyH37xWoS4pItUt+od48PY4jU0/3qzfPgK1t5fJr8Fs=
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8.2.1
    container_name: food-ordering-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongo-data:
    name: food-ordering-mongo-data
